version: '3.8'

services:
  redis:
    image: redis:7
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    image: ${DOCKERHUB_USERNAME:-nicolasmd}/portfolio:latest
    depends_on:
      redis:
        condition: service_healthy
    env_file: .env.${ENV:-production}
    environment:
      RAILS_ENV: ${ENV:-production}
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
    ports:
      - "127.0.0.1:3002:3000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    logging:
      driver: "json-file"
    volumes:
      - .:/app
      - .:/config
      - .:/public
      - .:/app/assets


volumes:
  redis_data: